__nodeDefine("stream", (module, exports, require) => {
  const EE = require("events");
  class Stream extends EE { pipe(dest, opts) { this.on("data", (c) => { if (dest.write(c) === false && this.pause) this.pause(); }); dest.on("drain", () => this.resume && this.resume()); if (!opts || opts.end !== false) this.on("end", () => dest.end && dest.end()); this.on("error", (e) => dest.emit("error", e)); return dest; } }
  class Readable extends Stream {
    constructor(opts = {}) { super(); this._buf = []; this._ended = false; this._flowing = null; this._reading = false; this._objectMode = !!opts.objectMode; this._encoding = opts.encoding || null; this.readable = true; this.readableEnded = false; this.destroyed = false; if (opts.read) this._read = opts.read; if (opts.destroy) this._destroy = opts.destroy; this.readableHighWaterMark = opts.highWaterMark || 16384; this.readableObjectMode = this._objectMode; }
    _read() {}
    push(chunk, enc) { if (chunk === null) { this._ended = true; this._flush(); return false; } if (typeof chunk === "string" && !this._objectMode) chunk = Buffer.from(chunk, enc); this._buf.push(chunk); this._flush(); return this._buf.length < 16; }
    unshift(chunk) { this._buf.unshift(chunk); }
    _flush() { if (this._flowing === false) return; if (this._flowing === null && this.listenerCount("data") === 0 && this.listenerCount("readable") === 0) return; if (this.listenerCount("readable")) { if (this._buf.length || this._ended) this.emit("readable"); } if (this._flowing !== true && this.listenerCount("readable")) return; queueMicrotask(() => { while (this._buf.length && this._flowing !== false) { let c = this._buf.shift(); if (this._encoding && Buffer.isBuffer(c)) c = c.toString(this._encoding); this.emit("data", c); } if (this._ended && !this._buf.length && !this.readableEnded) { this.readableEnded = true; this.readable = false; this.emit("end"); this.emit("close"); } else if (!this._ended && !this._reading) { this._reading = true; try { this._read(this.readableHighWaterMark); } finally { this._reading = false; } } }); }
    on(ev, fn) { super.on(ev, fn); if (ev === "data" && this._flowing !== false) { this._flowing = true; this._flush(); } if (ev === "readable") { this._flowing = false; queueMicrotask(() => { if (!this._reading) { this._reading = true; try { this._read(this.readableHighWaterMark); } finally { this._reading = false; } } if (this._buf.length || this._ended) this.emit("readable"); }); } return this; }
    read(n) { if (!this._buf.length) { if (this._ended && !this.readableEnded) { this.readableEnded = true; queueMicrotask(() => { this.emit("end"); this.emit("close"); }); } else if (!this._reading) { this._reading = true; try { this._read(this.readableHighWaterMark); } finally { this._reading = false; } } if (!this._buf.length) return null; } if (this._objectMode || n === undefined) { const all = this._objectMode ? this._buf.shift() : Buffer.concat(this._buf); if (!this._objectMode) this._buf = []; return this._encoding && Buffer.isBuffer(all) ? all.toString(this._encoding) : all; } const all = Buffer.concat(this._buf); this._buf = all.length > n ? [all.subarray(n)] : []; const out = all.subarray(0, n); return this._encoding ? out.toString(this._encoding) : out; }
    pause() { this._flowing = false; return this; } resume() { this._flowing = true; this._flush(); return this; } isPaused() { return this._flowing === false; }
    setEncoding(e) { this._encoding = e; return this; }
    destroy(err) { if (this.destroyed) return this; this.destroyed = true; this._ended = true; if (this._destroy) this._destroy(err, (e) => { if (e) this.emit("error", e); this.emit("close"); }); else { if (err) this.emit("error", err); this.emit("close"); } return this; }
    unpipe() { return this; } wrap(s) { s.on("data", (c) => this.push(c)); s.on("end", () => this.push(null)); return this; }
    async *[Symbol.asyncIterator]() { const q = []; let done = false, err = null, wake = null; this.on("data", (c) => { q.push(c); if (wake) { wake(); wake = null; } }); this.on("end", () => { done = true; if (wake) wake(); }); this.on("error", (e) => { err = e; if (wake) wake(); }); while (true) { if (q.length) yield q.shift(); else if (err) throw err; else if (done) return; else await new Promise((r) => { wake = r; }); } }
    static from(iter, opts) { const r = new Readable({ objectMode: true, ...opts }); (async () => { try { for await (const c of (typeof iter === "string" || Buffer.isBuffer(iter) ? [iter] : iter)) r.push(c); r.push(null); } catch (e) { r.destroy(e); } })(); return r; }
  }
  class Writable extends Stream {
    constructor(opts = {}) { super(); this.writable = true; this.writableEnded = false; this.writableFinished = false; this.destroyed = false; this._objectMode = !!opts.objectMode; if (opts.write) this._write = opts.write; if (opts.writev) this._writev = opts.writev; if (opts.final) this._final = opts.final; if (opts.destroy) this._destroy = opts.destroy; this.writableHighWaterMark = opts.highWaterMark || 16384; this._pending = 0; this._corked = 0; }
    _write(chunk, enc, cb) { cb(); }
    write(chunk, enc, cb) { if (typeof enc === "function") { cb = enc; enc = undefined; } if (this.writableEnded) { const e = new Error("write after end"); if (cb) cb(e); else this.emit("error", e); return false; } if (typeof chunk === "string" && !this._objectMode) chunk = Buffer.from(chunk, enc || "utf8"); this._pending++; this._write(chunk, enc || "buffer", (e) => { this._pending--; if (e) this.emit("error", e); if (cb) cb(e); if (!this._pending) { this.emit("drain"); this._maybeFinish(); } }); return this._pending < 16; }
    _maybeFinish() { if (this.writableEnded && !this._pending && !this.writableFinished) { const fin = () => { this.writableFinished = true; this.emit("finish"); this.emit("close"); }; if (this._final) this._final((e) => { if (e) this.emit("error", e); else fin(); }); else fin(); } }
    end(chunk, enc, cb) { if (typeof chunk === "function") { cb = chunk; chunk = undefined; } if (typeof enc === "function") { cb = enc; enc = undefined; } if (chunk != null) this.write(chunk, enc); this.writableEnded = true; this.writable = false; if (cb) this.once("finish", cb); queueMicrotask(() => this._maybeFinish()); return this; }
    cork() { this._corked++; } uncork() { this._corked = Math.max(0, this._corked - 1); } setDefaultEncoding() { return this; }
    destroy(err) { if (this.destroyed) return this; this.destroyed = true; if (this._destroy) this._destroy(err, (e) => { if (e) this.emit("error", e); this.emit("close"); }); else { if (err) this.emit("error", err); this.emit("close"); } return this; }
  }
  class Duplex extends Readable { constructor(opts = {}) { super(opts); this.writable = true; this.writableEnded = false; this.writableFinished = false; this._pending = 0; this._corked = 0; this.writableHighWaterMark = opts.highWaterMark || 16384; if (opts.write) this._write = opts.write; if (opts.final) this._final = opts.final; } }
  for (const k of ["write", "_write", "end", "_maybeFinish", "cork", "uncork", "setDefaultEncoding"]) Duplex.prototype[k] = Writable.prototype[k];
  Duplex.prototype.destroy = function (err) { Readable.prototype.destroy.call(this, err); return this; };
  class Transform extends Duplex {
    constructor(opts = {}) { super(opts); if (opts.transform) this._transform = opts.transform; if (opts.flush) this._flush2 = opts.flush; }
    _transform(chunk, enc, cb) { cb(null, chunk); }
    _write(chunk, enc, cb) { this._transform(chunk, enc, (e, out) => { if (e) return cb(e); if (out != null) this.push(out); cb(); }); }
    end(chunk, enc, cb) { if (typeof chunk === "function") { cb = chunk; chunk = undefined; } if (chunk != null) this.write(chunk, enc); this.writableEnded = true; const done = () => { this.push(null); this.writableFinished = true; this.emit("finish"); if (cb) cb(); }; queueMicrotask(() => { if (this._flush2) this._flush2((e, out) => { if (e) this.emit("error", e); if (out != null) this.push(out); done(); }); else done(); }); return this; }
  }
  class PassThrough extends Transform {}
  const finished = (s, opts, cb) => { if (typeof opts === "function") { cb = opts; } let done = false; const end = (e) => { if (!done) { done = true; cb(e); } }; s.once("end", () => end()); s.once("finish", () => end()); s.once("error", end); s.once("close", () => end()); return () => {}; };
  const pipeline = (...streams) => { const cb = typeof streams[streams.length - 1] === "function" ? streams.pop() : null; for (let i = 0; i < streams.length - 1; i++) streams[i].pipe(streams[i + 1]); const last = streams[streams.length - 1]; if (cb) finished(last, cb); return last; };
  const promises = { pipeline: (...s) => new Promise((res, rej) => pipeline(...s, (e) => (e ? rej(e) : res()))), finished: (s, o) => new Promise((res, rej) => finished(s, o, (e) => (e ? rej(e) : res()))) };
  Stream.Stream = Stream; Stream.Readable = Readable; Stream.Writable = Writable; Stream.Duplex = Duplex; Stream.Transform = Transform; Stream.PassThrough = PassThrough; Stream.finished = finished; Stream.pipeline = pipeline; Stream.promises = promises;
  Stream.addAbortSignal = (sig, s) => s; Stream.isReadable = (s) => s instanceof Readable; Stream.isWritable = (s) => s instanceof Writable;
  module.exports = Stream;
});
__nodeDefine("stream/promises", (module, exports, require) => { module.exports = require("stream").promises; });
__nodeDefine("stream/web", (module) => { module.exports = { ReadableStream: globalThis.ReadableStream, WritableStream: globalThis.WritableStream, TransformStream: globalThis.TransformStream, TextDecoderStream: globalThis.TextDecoderStream, TextEncoderStream: globalThis.TextEncoderStream }; });
