// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "OdeteEditor",
    platforms: [.iOS(.v26)],
    products: [
        .library(name: "OdeteEditor", targets: ["OdeteEditor"]),
    ],
    dependencies: [
        .package(path: "../OdeteI18n"),
        .package(path: "../OdeteCore"),
        .package(url: "https://github.com/simonbs/Runestone.git", from: "0.5.2"),
        .package(url: "https://github.com/simonbs/TreeSitterLanguages.git", from: "0.1.10"),
        // O runtime C do tree-sitter. Já vem pelo Runestone; aqui ele é declarado porque
        // a Odete fala com o parser direto, e não só pelo destaque de sintaxe.
        .package(url: "https://github.com/tree-sitter/tree-sitter", .upToNextMinor(from: "0.20.9")),
    ],
    targets: [
        .target(
            name: "OdeteEditor",
            dependencies: [
                .product(name: "OdeteI18n", package: "OdeteI18n"),
                .product(name: "OdeteCore", package: "OdeteCore"),
                .product(name: "Runestone", package: "Runestone"),
                .product(name: "TreeSitter", package: "tree-sitter"),
                .product(name: "TreeSitterAstro", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterBash", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCPP", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterC", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCSharp", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCSS", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterElixir", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterElm", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterGo", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterHaskell", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterHTML", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJava", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJavaScript", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJSON", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJulia", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterLaTeX", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterLua", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterMarkdown", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterOCaml", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPerl", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPHP", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPython", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterR", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRuby", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRust", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSCSS", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSQL", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSvelte", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSwift", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTOML", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTSX", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTypeScript", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterYAML", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterHTMLRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCSSRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJavaScriptRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTypeScriptRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTSXRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJSONRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterMarkdownRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterMarkdownInlineRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSwiftRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterYAMLRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterAstroRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSvelteRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRustRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCPPRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCSharpRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterGoRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJavaRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPythonRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRubyRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPHPRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterBashRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSQLRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterTOMLRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterLuaRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterPerlRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterHaskellRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterElixirRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterElmRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterOCamlRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJuliaRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterLaTeXRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterSCSSRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterCommentRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterJSDocRunestone", package: "TreeSitterLanguages"),
                .product(name: "TreeSitterRegexRunestone", package: "TreeSitterLanguages"),
            ],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "OdeteEditorTests",
            dependencies: ["OdeteEditor"],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
